// Code generated by cmd/glgen; DO NOT EDIT.
// Source: Khronos OpenGL XML registry (gl.xml), API: gl, Version: 2.1

package gl

import "unsafe"

// -----------------------------------------------------------------------------
// Constants
// -----------------------------------------------------------------------------

const (
	// Boolean
	FALSE = 0
	TRUE  = 1

	// Primitives
	POINTS         = 0x0000
	LINES          = 0x0001
	LINE_LOOP      = 0x0002
	LINE_STRIP     = 0x0003
	TRIANGLES      = 0x0004
	TRIANGLE_STRIP = 0x0005
	TRIANGLE_FAN   = 0x0006
	QUADS          = 0x0007

	// Errors
	NO_ERROR          = 0
	INVALID_ENUM      = 0x0500
	INVALID_VALUE     = 0x0501
	INVALID_OPERATION = 0x0502
	STACK_OVERFLOW    = 0x0503
	STACK_UNDERFLOW   = 0x0504
	OUT_OF_MEMORY     = 0x0505

	// String names
	VENDOR                   = 0x1F00
	RENDERER                 = 0x1F01
	VERSION                  = 0x1F02
	SHADING_LANGUAGE_VERSION = 0x8B8C
	EXTENSIONS               = 0x1F03

	// Texture targets
	TEXTURE_1D                = 0x0DE0
	TEXTURE_2D                = 0x0DE1
	TEXTURE_3D                = 0x806F
	TEXTURE_CUBE_MAP          = 0x8513
	TEXTURE_CUBE_MAP_POSITIVE_X = 0x8515
	TEXTURE_CUBE_MAP_NEGATIVE_X = 0x8516
	TEXTURE_CUBE_MAP_POSITIVE_Y = 0x8517
	TEXTURE_CUBE_MAP_NEGATIVE_Y = 0x8518
	TEXTURE_CUBE_MAP_POSITIVE_Z = 0x8519
	TEXTURE_CUBE_MAP_NEGATIVE_Z = 0x851A

	// Texture parameters
	TEXTURE_MIN_FILTER    = 0x2801
	TEXTURE_MAG_FILTER    = 0x2800
	TEXTURE_WRAP_S        = 0x2802
	TEXTURE_WRAP_T        = 0x2803
	TEXTURE_WRAP_R        = 0x8072
	NEAREST               = 0x2600
	LINEAR                = 0x2601
	NEAREST_MIPMAP_NEAREST = 0x2700
	LINEAR_MIPMAP_NEAREST  = 0x2701
	NEAREST_MIPMAP_LINEAR  = 0x2702
	LINEAR_MIPMAP_LINEAR   = 0x2703
	CLAMP_TO_EDGE         = 0x812F
	REPEAT                = 0x2901
	MIRRORED_REPEAT       = 0x8370

	// Texture units
	TEXTURE0  = 0x84C0
	TEXTURE1  = 0x84C1
	TEXTURE2  = 0x84C2
	TEXTURE3  = 0x84C3
	TEXTURE4  = 0x84C4
	TEXTURE5  = 0x84C5
	TEXTURE6  = 0x84C6
	TEXTURE7  = 0x84C7
	TEXTURE8  = 0x84C8
	TEXTURE9  = 0x84C9
	TEXTURE10 = 0x84CA
	TEXTURE11 = 0x84CB
	TEXTURE12 = 0x84CC
	TEXTURE13 = 0x84CD
	TEXTURE14 = 0x84CE
	TEXTURE15 = 0x84CF

	// Pixel formats
	DEPTH_COMPONENT = 0x1902
	RED             = 0x1903
	GREEN           = 0x1904
	BLUE            = 0x1905
	ALPHA           = 0x1906
	RGB             = 0x1907
	RGBA            = 0x1908
	LUMINANCE       = 0x1909
	LUMINANCE_ALPHA = 0x190A
	BGRA            = 0x80E1
	BGR             = 0x80E0

	// Pixel types
	UNSIGNED_BYTE  = 0x1401
	BYTE           = 0x1400
	UNSIGNED_SHORT = 0x1403
	SHORT          = 0x1402
	UNSIGNED_INT   = 0x1405
	INT            = 0x1404
	FLOAT          = 0x1406

	// Buffer clear bits
	DEPTH_BUFFER_BIT   = 0x00000100
	STENCIL_BUFFER_BIT = 0x00000400
	COLOR_BUFFER_BIT   = 0x00004000

	// Buffer targets
	ARRAY_BUFFER         = 0x8892
	ELEMENT_ARRAY_BUFFER = 0x8893
	UNIFORM_BUFFER       = 0x8A11

	// Buffer usage hints
	STREAM_DRAW  = 0x88E0
	STATIC_DRAW  = 0x88E4
	DYNAMIC_DRAW = 0x88E8

	// Framebuffer
	FRAMEBUFFER              = 0x8D40
	READ_FRAMEBUFFER         = 0x8CA8
	DRAW_FRAMEBUFFER         = 0x8CA9
	RENDERBUFFER             = 0x8D41
	COLOR_ATTACHMENT0        = 0x8CE0
	DEPTH_ATTACHMENT         = 0x8D00
	STENCIL_ATTACHMENT       = 0x8D20
	DEPTH_STENCIL_ATTACHMENT = 0x821A
	FRAMEBUFFER_COMPLETE     = 0x8CD5

	// Renderbuffer
	DEPTH_COMPONENT16  = 0x81A5
	DEPTH_COMPONENT24  = 0x81A6
	DEPTH_COMPONENT32F = 0x8CAC
	DEPTH24_STENCIL8   = 0x88F0

	// Blending
	ZERO                     = 0
	ONE                      = 1
	SRC_COLOR                = 0x0300
	ONE_MINUS_SRC_COLOR      = 0x0301
	SRC_ALPHA                = 0x0302
	ONE_MINUS_SRC_ALPHA      = 0x0303
	DST_ALPHA                = 0x0304
	ONE_MINUS_DST_ALPHA      = 0x0305
	DST_COLOR                = 0x0306
	ONE_MINUS_DST_COLOR      = 0x0307
	SRC_ALPHA_SATURATE       = 0x0308
	CONSTANT_COLOR           = 0x8001
	ONE_MINUS_CONSTANT_COLOR = 0x8002
	CONSTANT_ALPHA           = 0x8003
	ONE_MINUS_CONSTANT_ALPHA = 0x8004

	// Capabilities
	BLEND        = 0x0BE2
	CULL_FACE    = 0x0B44
	DEPTH_TEST   = 0x0B71
	SCISSOR_TEST = 0x0C11
	STENCIL_TEST = 0x0B90
	MULTISAMPLE  = 0x809D

	// Shader types
	VERTEX_SHADER   = 0x8B31
	FRAGMENT_SHADER = 0x8B30
	GEOMETRY_SHADER = 0x8DD9

	// Shader / program params
	DELETE_STATUS       = 0x8B80
	COMPILE_STATUS      = 0x8B81
	LINK_STATUS         = 0x8B82
	VALIDATE_STATUS     = 0x8B83
	INFO_LOG_LENGTH     = 0x8B84
	ACTIVE_UNIFORMS     = 0x8B86
	ACTIVE_ATTRIBUTES   = 0x8B89

	// Data types (for vertex attribs etc.)
	FLOAT_VEC2   = 0x8B50
	FLOAT_VEC3   = 0x8B51
	FLOAT_VEC4   = 0x8B52
	INT_VEC2     = 0x8B53
	INT_VEC3     = 0x8B54
	INT_VEC4     = 0x8B55
	BOOL         = 0x8B56
	FLOAT_MAT2   = 0x8B5A
	FLOAT_MAT3   = 0x8B5B
	FLOAT_MAT4   = 0x8B5C
	SAMPLER_2D   = 0x8B5E
	SAMPLER_CUBE = 0x8B60

	// Pixel storage
	PACK_ALIGNMENT   = 0x0D05
	UNPACK_ALIGNMENT = 0x0CF5

	// Read buffer
	FRONT = 0x0404
	BACK  = 0x0405

	// Polygon mode
	FRONT_AND_BACK = 0x0408
	FILL           = 0x1B02
	LINE           = 0x1B01
	POINT          = 0x1B00
)

// -----------------------------------------------------------------------------
// Public wrapper functions — identical signatures to github.com/go-gl/gl/v2.1/gl
// -----------------------------------------------------------------------------

func ActiveTexture(texture uint32)            { gpActiveTexture(texture) }
func AttachShader(program, shader uint32)      { gpAttachShader(program, shader) }
func BindBuffer(target, buffer uint32)         { gpBindBuffer(target, buffer) }
func BindFramebuffer(target, framebuffer uint32) { gpBindFramebuffer(target, framebuffer) }
func BindRenderbuffer(target, renderbuffer uint32) { gpBindRenderbuffer(target, renderbuffer) }
func BindTexture(target, texture uint32)       { gpBindTexture(target, texture) }
func BindVertexArray(array uint32)             { gpBindVertexArray(array) }
func BlendFunc(sfactor, dfactor uint32)        { gpBlendFunc(sfactor, dfactor) }

func BufferData(target uint32, size int, data unsafe.Pointer, usage uint32) {
	gpBufferData(target, size, data, usage)
}
func BufferSubData(target uint32, offset, size int, data unsafe.Pointer) {
	gpBufferSubData(target, offset, size, data)
}

func Clear(mask uint32)                                  { gpClear(mask) }
func ClearColor(red, green, blue, alpha float32)         { gpClearColor(red, green, blue, alpha) }
func CompileShader(shader uint32)                        { gpCompileShader(shader) }
func CreateProgram() uint32                              { return gpCreateProgram() }
func CreateShader(xtype uint32) uint32                   { return gpCreateShader(xtype) }

func DeleteBuffers(n int32, buffers *uint32)              { gpDeleteBuffers(n, buffers) }
func DeleteFramebuffers(n int32, framebuffers *uint32)    { gpDeleteFramebuffers(n, framebuffers) }
func DeleteProgram(program uint32)                        { gpDeleteProgram(program) }
func DeleteRenderbuffers(n int32, renderbuffers *uint32)  { gpDeleteRenderbuffers(n, renderbuffers) }
func DeleteShader(shader uint32)                          { gpDeleteShader(shader) }
func DeleteTextures(n int32, textures *uint32)            { gpDeleteTextures(n, textures) }
func DeleteVertexArrays(n int32, arrays *uint32)          { gpDeleteVertexArrays(n, arrays) }
func Disable(cap uint32)                                  { gpDisable(cap) }
func DrawArrays(mode uint32, first, count int32)          { gpDrawArrays(mode, first, count) }

func DrawElements(mode uint32, count int32, xtype uint32, indices unsafe.Pointer) {
	gpDrawElements(mode, count, xtype, indices)
}

func Enable(cap uint32)                              { gpEnable(cap) }
func EnableVertexAttribArray(index uint32)           { gpEnableVertexAttribArray(index) }

func FramebufferRenderbuffer(target, attachment, renderbuffertarget, renderbuffer uint32) {
	gpFramebufferRenderbuffer(target, attachment, renderbuffertarget, renderbuffer)
}
func FramebufferTexture2D(target, attachment, textarget, texture uint32, level int32) {
	gpFramebufferTexture2D(target, attachment, textarget, texture, level)
}

func GenBuffers(n int32, buffers *uint32)              { gpGenBuffers(n, buffers) }
func GenFramebuffers(n int32, ids *uint32)             { gpGenFramebuffers(n, ids) }
func GenRenderbuffers(n int32, renderbuffers *uint32)  { gpGenRenderbuffers(n, renderbuffers) }
func GenTextures(n int32, textures *uint32)            { gpGenTextures(n, textures) }
func GenVertexArrays(n int32, arrays *uint32)          { gpGenVertexArrays(n, arrays) }

func GetAttribLocation(program uint32, name *uint8) int32 {
	return gpGetAttribLocation(program, name)
}
func GetError() uint32                           { return gpGetError() }
func GetIntegerv(pname uint32, data *int32)      { gpGetIntegerv(pname, data) }

func GetProgramInfoLog(program uint32, bufSize int32, length *int32, infoLog *uint8) {
	gpGetProgramInfoLog(program, bufSize, length, infoLog)
}
func GetProgramiv(program, pname uint32, params *int32) { gpGetProgramiv(program, pname, params) }

func GetShaderInfoLog(shader uint32, bufSize int32, length *int32, infoLog *uint8) {
	gpGetShaderInfoLog(shader, bufSize, length, infoLog)
}
func GetShaderiv(shader, pname uint32, params *int32) { gpGetShaderiv(shader, pname, params) }
func GetString(name uint32) *uint8                    { return gpGetString(name) }

func GetUniformLocation(program uint32, name *uint8) int32 {
	return gpGetUniformLocation(program, name)
}

func LinkProgram(program uint32)                        { gpLinkProgram(program) }
func PixelStorei(pname uint32, param int32)             { gpPixelStorei(pname, param) }
func ReadBuffer(src uint32)                             { gpReadBuffer(src) }

func ReadPixels(x, y, width, height int32, format, xtype uint32, pixels unsafe.Pointer) {
	gpReadPixels(x, y, width, height, format, xtype, pixels)
}

func RenderbufferStorage(target, internalformat uint32, width, height int32) {
	gpRenderbufferStorage(target, internalformat, width, height)
}
func Scissor(x, y, width, height int32) { gpScissor(x, y, width, height) }

func ShaderSource(shader uint32, count int32, xstring **uint8, length *int32) {
	gpShaderSource(shader, count, xstring, length)
}

func TexImage2D(target uint32, level, internalformat, width, height, border int32, format, xtype uint32, pixels unsafe.Pointer) {
	gpTexImage2D(target, level, internalformat, width, height, border, format, xtype, pixels)
}
func TexParameteri(target, pname uint32, param int32) { gpTexParameteri(target, pname, param) }

func Uniform1f(location int32, v0 float32)                    { gpUniform1f(location, v0) }
func Uniform1i(location, v0 int32)                            { gpUniform1i(location, v0) }
func Uniform2f(location int32, v0, v1 float32)                { gpUniform2f(location, v0, v1) }
func Uniform4f(location int32, v0, v1, v2, v3 float32)        { gpUniform4f(location, v0, v1, v2, v3) }
func UniformMatrix4fv(location, count int32, transpose bool, value *float32) {
	gpUniformMatrix4fv(location, count, transpose, value)
}

func UseProgram(program uint32) { gpUseProgram(program) }

func VertexAttribPointer(index uint32, size int32, xtype uint32, normalized bool, stride int32, pointer unsafe.Pointer) {
	gpVertexAttribPointer(index, size, xtype, normalized, stride, pointer)
}

func Viewport(x, y, width, height int32) { gpViewport(x, y, width, height) }
