// Code generated by cmd/glgen; DO NOT EDIT.
// Source: Khronos OpenGL XML registry (gl.xml), API: gles2, Version: 3.1

package gl

import "unsafe"

// -----------------------------------------------------------------------------
// Constants
// -----------------------------------------------------------------------------

const (
	ACTIVE_ATOMIC_COUNTER_BUFFERS = 0x92D9
	ACTIVE_ATTRIBUTES = 0x8B89
	ACTIVE_ATTRIBUTE_MAX_LENGTH = 0x8B8A
	ACTIVE_PROGRAM = 0x8259
	ACTIVE_RESOURCES = 0x92F5
	ACTIVE_TEXTURE = 0x84E0
	ACTIVE_UNIFORMS = 0x8B86
	ACTIVE_UNIFORM_BLOCKS = 0x8A36
	ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH = 0x8A35
	ACTIVE_UNIFORM_MAX_LENGTH = 0x8B87
	ACTIVE_VARIABLES = 0x9305
	ALIASED_LINE_WIDTH_RANGE = 0x846E
	ALIASED_POINT_SIZE_RANGE = 0x846D
	ALL_BARRIER_BITS = 0xFFFFFFFF
	ALL_SHADER_BITS = 0xFFFFFFFF
	ALPHA = 0x1906
	ALPHA_BITS = 0x0D55
	ALREADY_SIGNALED = 0x911A
	ALWAYS = 0x0207
	ANY_SAMPLES_PASSED = 0x8C2F
	ANY_SAMPLES_PASSED_CONSERVATIVE = 0x8D6A
	ARRAY_BUFFER = 0x8892
	ARRAY_BUFFER_BINDING = 0x8894
	ARRAY_SIZE = 0x92FB
	ARRAY_STRIDE = 0x92FE
	ATOMIC_COUNTER_BARRIER_BIT = 0x00001000
	ATOMIC_COUNTER_BUFFER = 0x92C0
	ATOMIC_COUNTER_BUFFER_BINDING = 0x92C1
	ATOMIC_COUNTER_BUFFER_INDEX = 0x9301
	ATOMIC_COUNTER_BUFFER_SIZE = 0x92C3
	ATOMIC_COUNTER_BUFFER_START = 0x92C2
	ATTACHED_SHADERS = 0x8B85
	BACK = 0x0405
	BLEND = 0x0BE2
	BLEND_COLOR = 0x8005
	BLEND_DST_ALPHA = 0x80CA
	BLEND_DST_RGB = 0x80C8
	BLEND_EQUATION = 0x8009
	BLEND_EQUATION_ALPHA = 0x883D
	BLEND_EQUATION_RGB = 0x8009
	BLEND_SRC_ALPHA = 0x80CB
	BLEND_SRC_RGB = 0x80C9
	BLOCK_INDEX = 0x92FD
	BLUE = 0x1905
	BLUE_BITS = 0x0D54
	BOOL = 0x8B56
	BOOL_VEC2 = 0x8B57
	BOOL_VEC3 = 0x8B58
	BOOL_VEC4 = 0x8B59
	BUFFER_ACCESS_FLAGS = 0x911F
	BUFFER_BINDING = 0x9302
	BUFFER_DATA_SIZE = 0x9303
	BUFFER_MAPPED = 0x88BC
	BUFFER_MAP_LENGTH = 0x9120
	BUFFER_MAP_OFFSET = 0x9121
	BUFFER_MAP_POINTER = 0x88BD
	BUFFER_SIZE = 0x8764
	BUFFER_UPDATE_BARRIER_BIT = 0x00000200
	BUFFER_USAGE = 0x8765
	BUFFER_VARIABLE = 0x92E5
	BYTE = 0x1400
	CCW = 0x0901
	CLAMP_TO_EDGE = 0x812F
	COLOR = 0x1800
	COLOR_ATTACHMENT0 = 0x8CE0
	COLOR_ATTACHMENT1 = 0x8CE1
	COLOR_ATTACHMENT10 = 0x8CEA
	COLOR_ATTACHMENT11 = 0x8CEB
	COLOR_ATTACHMENT12 = 0x8CEC
	COLOR_ATTACHMENT13 = 0x8CED
	COLOR_ATTACHMENT14 = 0x8CEE
	COLOR_ATTACHMENT15 = 0x8CEF
	COLOR_ATTACHMENT16 = 0x8CF0
	COLOR_ATTACHMENT17 = 0x8CF1
	COLOR_ATTACHMENT18 = 0x8CF2
	COLOR_ATTACHMENT19 = 0x8CF3
	COLOR_ATTACHMENT2 = 0x8CE2
	COLOR_ATTACHMENT20 = 0x8CF4
	COLOR_ATTACHMENT21 = 0x8CF5
	COLOR_ATTACHMENT22 = 0x8CF6
	COLOR_ATTACHMENT23 = 0x8CF7
	COLOR_ATTACHMENT24 = 0x8CF8
	COLOR_ATTACHMENT25 = 0x8CF9
	COLOR_ATTACHMENT26 = 0x8CFA
	COLOR_ATTACHMENT27 = 0x8CFB
	COLOR_ATTACHMENT28 = 0x8CFC
	COLOR_ATTACHMENT29 = 0x8CFD
	COLOR_ATTACHMENT3 = 0x8CE3
	COLOR_ATTACHMENT30 = 0x8CFE
	COLOR_ATTACHMENT31 = 0x8CFF
	COLOR_ATTACHMENT4 = 0x8CE4
	COLOR_ATTACHMENT5 = 0x8CE5
	COLOR_ATTACHMENT6 = 0x8CE6
	COLOR_ATTACHMENT7 = 0x8CE7
	COLOR_ATTACHMENT8 = 0x8CE8
	COLOR_ATTACHMENT9 = 0x8CE9
	COLOR_BUFFER_BIT = 0x00004000
	COLOR_CLEAR_VALUE = 0x0C22
	COLOR_WRITEMASK = 0x0C23
	COMMAND_BARRIER_BIT = 0x00000040
	COMPARE_REF_TO_TEXTURE = 0x884E
	COMPILE_STATUS = 0x8B81
	COMPRESSED_R11_EAC = 0x9270
	COMPRESSED_RG11_EAC = 0x9272
	COMPRESSED_RGB8_ETC2 = 0x9274
	COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2 = 0x9276
	COMPRESSED_RGBA8_ETC2_EAC = 0x9278
	COMPRESSED_SIGNED_R11_EAC = 0x9271
	COMPRESSED_SIGNED_RG11_EAC = 0x9273
	COMPRESSED_SRGB8_ALPHA8_ETC2_EAC = 0x9279
	COMPRESSED_SRGB8_ETC2 = 0x9275
	COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2 = 0x9277
	COMPRESSED_TEXTURE_FORMATS = 0x86A3
	COMPUTE_SHADER = 0x91B9
	COMPUTE_SHADER_BIT = 0x00000020
	COMPUTE_WORK_GROUP_SIZE = 0x8267
	CONDITION_SATISFIED = 0x911C
	CONSTANT_ALPHA = 0x8003
	CONSTANT_COLOR = 0x8001
	COPY_READ_BUFFER = 0x8F36
	COPY_READ_BUFFER_BINDING = 0x8F36
	COPY_WRITE_BUFFER = 0x8F37
	COPY_WRITE_BUFFER_BINDING = 0x8F37
	CULL_FACE = 0x0B44
	CULL_FACE_MODE = 0x0B45
	CURRENT_PROGRAM = 0x8B8D
	CURRENT_QUERY = 0x8865
	CURRENT_VERTEX_ATTRIB = 0x8626
	CW = 0x0900
	DECR = 0x1E03
	DECR_WRAP = 0x8508
	DELETE_STATUS = 0x8B80
	DEPTH = 0x1801
	DEPTH24_STENCIL8 = 0x88F0
	DEPTH32F_STENCIL8 = 0x8CAD
	DEPTH_ATTACHMENT = 0x8D00
	DEPTH_BITS = 0x0D56
	DEPTH_BUFFER_BIT = 0x00000100
	DEPTH_CLEAR_VALUE = 0x0B73
	DEPTH_COMPONENT = 0x1902
	DEPTH_COMPONENT16 = 0x81A5
	DEPTH_COMPONENT24 = 0x81A6
	DEPTH_COMPONENT32F = 0x8CAC
	DEPTH_FUNC = 0x0B74
	DEPTH_RANGE = 0x0B70
	DEPTH_STENCIL = 0x84F9
	DEPTH_STENCIL_ATTACHMENT = 0x821A
	DEPTH_STENCIL_TEXTURE_MODE = 0x90EA
	DEPTH_TEST = 0x0B71
	DEPTH_WRITEMASK = 0x0B72
	DISPATCH_INDIRECT_BUFFER = 0x90EE
	DISPATCH_INDIRECT_BUFFER_BINDING = 0x90EF
	DITHER = 0x0BD0
	DONT_CARE = 0x1100
	DRAW_BUFFER0 = 0x8825
	DRAW_BUFFER1 = 0x8826
	DRAW_BUFFER10 = 0x882F
	DRAW_BUFFER11 = 0x8830
	DRAW_BUFFER12 = 0x8831
	DRAW_BUFFER13 = 0x8832
	DRAW_BUFFER14 = 0x8833
	DRAW_BUFFER15 = 0x8834
	DRAW_BUFFER2 = 0x8827
	DRAW_BUFFER3 = 0x8828
	DRAW_BUFFER4 = 0x8829
	DRAW_BUFFER5 = 0x882A
	DRAW_BUFFER6 = 0x882B
	DRAW_BUFFER7 = 0x882C
	DRAW_BUFFER8 = 0x882D
	DRAW_BUFFER9 = 0x882E
	DRAW_FRAMEBUFFER = 0x8CA9
	DRAW_FRAMEBUFFER_BINDING = 0x8CA6
	DRAW_INDIRECT_BUFFER = 0x8F3F
	DRAW_INDIRECT_BUFFER_BINDING = 0x8F43
	DST_ALPHA = 0x0304
	DST_COLOR = 0x0306
	DYNAMIC_COPY = 0x88EA
	DYNAMIC_DRAW = 0x88E8
	DYNAMIC_READ = 0x88E9
	ELEMENT_ARRAY_BARRIER_BIT = 0x00000002
	ELEMENT_ARRAY_BUFFER = 0x8893
	ELEMENT_ARRAY_BUFFER_BINDING = 0x8895
	EQUAL = 0x0202
	EXTENSIONS = 0x1F03
	FALSE = 0
	FASTEST = 0x1101
	FIXED = 0x140C
	FLOAT = 0x1406
	FLOAT_32_UNSIGNED_INT_24_8_REV = 0x8DAD
	FLOAT_MAT2 = 0x8B5A
	FLOAT_MAT2x3 = 0x8B65
	FLOAT_MAT2x4 = 0x8B66
	FLOAT_MAT3 = 0x8B5B
	FLOAT_MAT3x2 = 0x8B67
	FLOAT_MAT3x4 = 0x8B68
	FLOAT_MAT4 = 0x8B5C
	FLOAT_MAT4x2 = 0x8B69
	FLOAT_MAT4x3 = 0x8B6A
	FLOAT_VEC2 = 0x8B50
	FLOAT_VEC3 = 0x8B51
	FLOAT_VEC4 = 0x8B52
	FRAGMENT_SHADER = 0x8B30
	FRAGMENT_SHADER_BIT = 0x00000002
	FRAGMENT_SHADER_DERIVATIVE_HINT = 0x8B8B
	FRAMEBUFFER = 0x8D40
	FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE = 0x8215
	FRAMEBUFFER_ATTACHMENT_BLUE_SIZE = 0x8214
	FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING = 0x8210
	FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE = 0x8211
	FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE = 0x8216
	FRAMEBUFFER_ATTACHMENT_GREEN_SIZE = 0x8213
	FRAMEBUFFER_ATTACHMENT_OBJECT_NAME = 0x8CD1
	FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE = 0x8CD0
	FRAMEBUFFER_ATTACHMENT_RED_SIZE = 0x8212
	FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE = 0x8217
	FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE = 0x8CD3
	FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER = 0x8CD4
	FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL = 0x8CD2
	FRAMEBUFFER_BARRIER_BIT = 0x00000400
	FRAMEBUFFER_BINDING = 0x8CA6
	FRAMEBUFFER_COMPLETE = 0x8CD5
	FRAMEBUFFER_DEFAULT = 0x8218
	FRAMEBUFFER_DEFAULT_FIXED_SAMPLE_LOCATIONS = 0x9314
	FRAMEBUFFER_DEFAULT_HEIGHT = 0x9311
	FRAMEBUFFER_DEFAULT_SAMPLES = 0x9313
	FRAMEBUFFER_DEFAULT_WIDTH = 0x9310
	FRAMEBUFFER_INCOMPLETE_ATTACHMENT = 0x8CD6
	FRAMEBUFFER_INCOMPLETE_DIMENSIONS = 0x8CD9
	FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = 0x8CD7
	FRAMEBUFFER_INCOMPLETE_MULTISAMPLE = 0x8D56
	FRAMEBUFFER_UNDEFINED = 0x8219
	FRAMEBUFFER_UNSUPPORTED = 0x8CDD
	FRONT = 0x0404
	FRONT_AND_BACK = 0x0408
	FRONT_FACE = 0x0B46
	FUNC_ADD = 0x8006
	FUNC_REVERSE_SUBTRACT = 0x800B
	FUNC_SUBTRACT = 0x800A
	GENERATE_MIPMAP_HINT = 0x8192
	GEQUAL = 0x0206
	GREATER = 0x0204
	GREEN = 0x1904
	GREEN_BITS = 0x0D53
	HALF_FLOAT = 0x140B
	HIGH_FLOAT = 0x8DF2
	HIGH_INT = 0x8DF5
	IMAGE_2D = 0x904D
	IMAGE_2D_ARRAY = 0x9053
	IMAGE_3D = 0x904E
	IMAGE_BINDING_ACCESS = 0x8F3E
	IMAGE_BINDING_FORMAT = 0x906E
	IMAGE_BINDING_LAYER = 0x8F3D
	IMAGE_BINDING_LAYERED = 0x8F3C
	IMAGE_BINDING_LEVEL = 0x8F3B
	IMAGE_BINDING_NAME = 0x8F3A
	IMAGE_CUBE = 0x9050
	IMAGE_FORMAT_COMPATIBILITY_BY_CLASS = 0x90C9
	IMAGE_FORMAT_COMPATIBILITY_BY_SIZE = 0x90C8
	IMAGE_FORMAT_COMPATIBILITY_TYPE = 0x90C7
	IMPLEMENTATION_COLOR_READ_FORMAT = 0x8B9B
	IMPLEMENTATION_COLOR_READ_TYPE = 0x8B9A
	INCR = 0x1E02
	INCR_WRAP = 0x8507
	INFO_LOG_LENGTH = 0x8B84
	INT = 0x1404
	INTERLEAVED_ATTRIBS = 0x8C8C
	INT_2_10_10_10_REV = 0x8D9F
	INT_IMAGE_2D = 0x9058
	INT_IMAGE_2D_ARRAY = 0x905E
	INT_IMAGE_3D = 0x9059
	INT_IMAGE_CUBE = 0x905B
	INT_SAMPLER_2D = 0x8DCA
	INT_SAMPLER_2D_ARRAY = 0x8DCF
	INT_SAMPLER_2D_MULTISAMPLE = 0x9109
	INT_SAMPLER_3D = 0x8DCB
	INT_SAMPLER_CUBE = 0x8DCC
	INT_VEC2 = 0x8B53
	INT_VEC3 = 0x8B54
	INT_VEC4 = 0x8B55
	INVALID_ENUM = 0x0500
	INVALID_FRAMEBUFFER_OPERATION = 0x0506
	INVALID_INDEX = 0xFFFFFFFF
	INVALID_OPERATION = 0x0502
	INVALID_VALUE = 0x0501
	INVERT = 0x150A
	IS_ROW_MAJOR = 0x9300
	KEEP = 0x1E00
	LEQUAL = 0x0203
	LESS = 0x0201
	LINEAR = 0x2601
	LINEAR_MIPMAP_LINEAR = 0x2703
	LINEAR_MIPMAP_NEAREST = 0x2701
	LINES = 0x0001
	LINE_LOOP = 0x0002
	LINE_STRIP = 0x0003
	LINE_WIDTH = 0x0B21
	LINK_STATUS = 0x8B82
	LOCATION = 0x930E
	LOW_FLOAT = 0x8DF0
	LOW_INT = 0x8DF3
	LUMINANCE = 0x1909
	LUMINANCE_ALPHA = 0x190A
	MAJOR_VERSION = 0x821B
	MAP_FLUSH_EXPLICIT_BIT = 0x0010
	MAP_INVALIDATE_BUFFER_BIT = 0x0008
	MAP_INVALIDATE_RANGE_BIT = 0x0004
	MAP_READ_BIT = 0x0001
	MAP_UNSYNCHRONIZED_BIT = 0x0020
	MAP_WRITE_BIT = 0x0002
	MATRIX_STRIDE = 0x92FF
	MAX = 0x8008
	MAX_3D_TEXTURE_SIZE = 0x8073
	MAX_ARRAY_TEXTURE_LAYERS = 0x88FF
	MAX_ATOMIC_COUNTER_BUFFER_BINDINGS = 0x92DC
	MAX_ATOMIC_COUNTER_BUFFER_SIZE = 0x92D8
	MAX_COLOR_ATTACHMENTS = 0x8CDF
	MAX_COLOR_TEXTURE_SAMPLES = 0x910E
	MAX_COMBINED_ATOMIC_COUNTERS = 0x92D7
	MAX_COMBINED_ATOMIC_COUNTER_BUFFERS = 0x92D1
	MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS = 0x8266
	MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS = 0x8A33
	MAX_COMBINED_IMAGE_UNIFORMS = 0x90CF
	MAX_COMBINED_SHADER_OUTPUT_RESOURCES = 0x8F39
	MAX_COMBINED_SHADER_STORAGE_BLOCKS = 0x90DC
	MAX_COMBINED_TEXTURE_IMAGE_UNITS = 0x8B4D
	MAX_COMBINED_UNIFORM_BLOCKS = 0x8A2E
	MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS = 0x8A31
	MAX_COMPUTE_ATOMIC_COUNTERS = 0x8265
	MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS = 0x8264
	MAX_COMPUTE_IMAGE_UNIFORMS = 0x91BD
	MAX_COMPUTE_SHADER_STORAGE_BLOCKS = 0x90DB
	MAX_COMPUTE_SHARED_MEMORY_SIZE = 0x8262
	MAX_COMPUTE_TEXTURE_IMAGE_UNITS = 0x91BC
	MAX_COMPUTE_UNIFORM_BLOCKS = 0x91BB
	MAX_COMPUTE_UNIFORM_COMPONENTS = 0x8263
	MAX_COMPUTE_WORK_GROUP_COUNT = 0x91BE
	MAX_COMPUTE_WORK_GROUP_INVOCATIONS = 0x90EB
	MAX_COMPUTE_WORK_GROUP_SIZE = 0x91BF
	MAX_CUBE_MAP_TEXTURE_SIZE = 0x851C
	MAX_DEPTH_TEXTURE_SAMPLES = 0x910F
	MAX_DRAW_BUFFERS = 0x8824
	MAX_ELEMENTS_INDICES = 0x80E9
	MAX_ELEMENTS_VERTICES = 0x80E8
	MAX_ELEMENT_INDEX = 0x8D6B
	MAX_FRAGMENT_ATOMIC_COUNTERS = 0x92D6
	MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS = 0x92D0
	MAX_FRAGMENT_IMAGE_UNIFORMS = 0x90CE
	MAX_FRAGMENT_INPUT_COMPONENTS = 0x9125
	MAX_FRAGMENT_SHADER_STORAGE_BLOCKS = 0x90DA
	MAX_FRAGMENT_UNIFORM_BLOCKS = 0x8A2D
	MAX_FRAGMENT_UNIFORM_COMPONENTS = 0x8B49
	MAX_FRAGMENT_UNIFORM_VECTORS = 0x8DFD
	MAX_FRAMEBUFFER_HEIGHT = 0x9316
	MAX_FRAMEBUFFER_SAMPLES = 0x9318
	MAX_FRAMEBUFFER_WIDTH = 0x9315
	MAX_IMAGE_UNITS = 0x8F38
	MAX_INTEGER_SAMPLES = 0x9110
	MAX_NAME_LENGTH = 0x92F6
	MAX_NUM_ACTIVE_VARIABLES = 0x92F7
	MAX_PROGRAM_TEXEL_OFFSET = 0x8905
	MAX_PROGRAM_TEXTURE_GATHER_OFFSET = 0x8E5F
	MAX_RENDERBUFFER_SIZE = 0x84E8
	MAX_SAMPLES = 0x8D57
	MAX_SAMPLE_MASK_WORDS = 0x8E59
	MAX_SERVER_WAIT_TIMEOUT = 0x9111
	MAX_SHADER_STORAGE_BLOCK_SIZE = 0x90DE
	MAX_SHADER_STORAGE_BUFFER_BINDINGS = 0x90DD
	MAX_TEXTURE_IMAGE_UNITS = 0x8872
	MAX_TEXTURE_LOD_BIAS = 0x84FD
	MAX_TEXTURE_SIZE = 0x0D33
	MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS = 0x8C8A
	MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS = 0x8C8B
	MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS = 0x8C80
	MAX_UNIFORM_BLOCK_SIZE = 0x8A30
	MAX_UNIFORM_BUFFER_BINDINGS = 0x8A2F
	MAX_UNIFORM_LOCATIONS = 0x826E
	MAX_VARYING_COMPONENTS = 0x8B4B
	MAX_VARYING_VECTORS = 0x8DFC
	MAX_VERTEX_ATOMIC_COUNTERS = 0x92D2
	MAX_VERTEX_ATOMIC_COUNTER_BUFFERS = 0x92CC
	MAX_VERTEX_ATTRIBS = 0x8869
	MAX_VERTEX_ATTRIB_BINDINGS = 0x82DA
	MAX_VERTEX_ATTRIB_RELATIVE_OFFSET = 0x82D9
	MAX_VERTEX_ATTRIB_STRIDE = 0x82E5
	MAX_VERTEX_IMAGE_UNIFORMS = 0x90CA
	MAX_VERTEX_OUTPUT_COMPONENTS = 0x9122
	MAX_VERTEX_SHADER_STORAGE_BLOCKS = 0x90D6
	MAX_VERTEX_TEXTURE_IMAGE_UNITS = 0x8B4C
	MAX_VERTEX_UNIFORM_BLOCKS = 0x8A2B
	MAX_VERTEX_UNIFORM_COMPONENTS = 0x8B4A
	MAX_VERTEX_UNIFORM_VECTORS = 0x8DFB
	MAX_VIEWPORT_DIMS = 0x0D3A
	MEDIUM_FLOAT = 0x8DF1
	MEDIUM_INT = 0x8DF4
	MIN = 0x8007
	MINOR_VERSION = 0x821C
	MIN_PROGRAM_TEXEL_OFFSET = 0x8904
	MIN_PROGRAM_TEXTURE_GATHER_OFFSET = 0x8E5E
	MIRRORED_REPEAT = 0x8370
	NAME_LENGTH = 0x92F9
	NEAREST = 0x2600
	NEAREST_MIPMAP_LINEAR = 0x2702
	NEAREST_MIPMAP_NEAREST = 0x2700
	NEVER = 0x0200
	NICEST = 0x1102
	NONE = 0
	NOTEQUAL = 0x0205
	NO_ERROR = 0
	NUM_ACTIVE_VARIABLES = 0x9304
	NUM_COMPRESSED_TEXTURE_FORMATS = 0x86A2
	NUM_EXTENSIONS = 0x821D
	NUM_PROGRAM_BINARY_FORMATS = 0x87FE
	NUM_SAMPLE_COUNTS = 0x9380
	NUM_SHADER_BINARY_FORMATS = 0x8DF9
	OBJECT_TYPE = 0x9112
	OFFSET = 0x92FC
	ONE = 1
	ONE_MINUS_CONSTANT_ALPHA = 0x8004
	ONE_MINUS_CONSTANT_COLOR = 0x8002
	ONE_MINUS_DST_ALPHA = 0x0305
	ONE_MINUS_DST_COLOR = 0x0307
	ONE_MINUS_SRC_ALPHA = 0x0303
	ONE_MINUS_SRC_COLOR = 0x0301
	OUT_OF_MEMORY = 0x0505
	PACK_ALIGNMENT = 0x0D05
	PACK_ROW_LENGTH = 0x0D02
	PACK_SKIP_PIXELS = 0x0D04
	PACK_SKIP_ROWS = 0x0D03
	PIXEL_BUFFER_BARRIER_BIT = 0x00000080
	PIXEL_PACK_BUFFER = 0x88EB
	PIXEL_PACK_BUFFER_BINDING = 0x88ED
	PIXEL_UNPACK_BUFFER = 0x88EC
	PIXEL_UNPACK_BUFFER_BINDING = 0x88EF
	POINTS = 0x0000
	POLYGON_OFFSET_FACTOR = 0x8038
	POLYGON_OFFSET_FILL = 0x8037
	POLYGON_OFFSET_UNITS = 0x2A00
	PRIMITIVE_RESTART_FIXED_INDEX = 0x8D69
	PROGRAM_BINARY_FORMATS = 0x87FF
	PROGRAM_BINARY_LENGTH = 0x8741
	PROGRAM_BINARY_RETRIEVABLE_HINT = 0x8257
	PROGRAM_INPUT = 0x92E3
	PROGRAM_OUTPUT = 0x92E4
	PROGRAM_PIPELINE_BINDING = 0x825A
	PROGRAM_SEPARABLE = 0x8258
	QUERY_RESULT = 0x8866
	QUERY_RESULT_AVAILABLE = 0x8867
	R11F_G11F_B10F = 0x8C3A
	R16F = 0x822D
	R16I = 0x8233
	R16UI = 0x8234
	R32F = 0x822E
	R32I = 0x8235
	R32UI = 0x8236
	R8 = 0x8229
	R8I = 0x8231
	R8UI = 0x8232
	R8_SNORM = 0x8F94
	RASTERIZER_DISCARD = 0x8C89
	READ_BUFFER = 0x0C02
	READ_FRAMEBUFFER = 0x8CA8
	READ_FRAMEBUFFER_BINDING = 0x8CAA
	READ_ONLY = 0x88B8
	READ_WRITE = 0x88BA
	RED = 0x1903
	RED_BITS = 0x0D52
	RED_INTEGER = 0x8D94
	REFERENCED_BY_COMPUTE_SHADER = 0x930B
	REFERENCED_BY_FRAGMENT_SHADER = 0x930A
	REFERENCED_BY_VERTEX_SHADER = 0x9306
	RENDERBUFFER = 0x8D41
	RENDERBUFFER_ALPHA_SIZE = 0x8D53
	RENDERBUFFER_BINDING = 0x8CA7
	RENDERBUFFER_BLUE_SIZE = 0x8D52
	RENDERBUFFER_DEPTH_SIZE = 0x8D54
	RENDERBUFFER_GREEN_SIZE = 0x8D51
	RENDERBUFFER_HEIGHT = 0x8D43
	RENDERBUFFER_INTERNAL_FORMAT = 0x8D44
	RENDERBUFFER_RED_SIZE = 0x8D50
	RENDERBUFFER_SAMPLES = 0x8CAB
	RENDERBUFFER_STENCIL_SIZE = 0x8D55
	RENDERBUFFER_WIDTH = 0x8D42
	RENDERER = 0x1F01
	REPEAT = 0x2901
	REPLACE = 0x1E01
	RG = 0x8227
	RG16F = 0x822F
	RG16I = 0x8239
	RG16UI = 0x823A
	RG32F = 0x8230
	RG32I = 0x823B
	RG32UI = 0x823C
	RG8 = 0x822B
	RG8I = 0x8237
	RG8UI = 0x8238
	RG8_SNORM = 0x8F95
	RGB = 0x1907
	RGB10_A2 = 0x8059
	RGB10_A2UI = 0x906F
	RGB16F = 0x881B
	RGB16I = 0x8D89
	RGB16UI = 0x8D77
	RGB32F = 0x8815
	RGB32I = 0x8D83
	RGB32UI = 0x8D71
	RGB565 = 0x8D62
	RGB5_A1 = 0x8057
	RGB8 = 0x8051
	RGB8I = 0x8D8F
	RGB8UI = 0x8D7D
	RGB8_SNORM = 0x8F96
	RGB9_E5 = 0x8C3D
	RGBA = 0x1908
	RGBA16F = 0x881A
	RGBA16I = 0x8D88
	RGBA16UI = 0x8D76
	RGBA32F = 0x8814
	RGBA32I = 0x8D82
	RGBA32UI = 0x8D70
	RGBA4 = 0x8056
	RGBA8 = 0x8058
	RGBA8I = 0x8D8E
	RGBA8UI = 0x8D7C
	RGBA8_SNORM = 0x8F97
	RGBA_INTEGER = 0x8D99
	RGB_INTEGER = 0x8D98
	RG_INTEGER = 0x8228
	SAMPLER_2D = 0x8B5E
	SAMPLER_2D_ARRAY = 0x8DC1
	SAMPLER_2D_ARRAY_SHADOW = 0x8DC4
	SAMPLER_2D_MULTISAMPLE = 0x9108
	SAMPLER_2D_SHADOW = 0x8B62
	SAMPLER_3D = 0x8B5F
	SAMPLER_BINDING = 0x8919
	SAMPLER_CUBE = 0x8B60
	SAMPLER_CUBE_SHADOW = 0x8DC5
	SAMPLES = 0x80A9
	SAMPLE_ALPHA_TO_COVERAGE = 0x809E
	SAMPLE_BUFFERS = 0x80A8
	SAMPLE_COVERAGE = 0x80A0
	SAMPLE_COVERAGE_INVERT = 0x80AB
	SAMPLE_COVERAGE_VALUE = 0x80AA
	SAMPLE_MASK = 0x8E51
	SAMPLE_MASK_VALUE = 0x8E52
	SAMPLE_POSITION = 0x8E50
	SCISSOR_BOX = 0x0C10
	SCISSOR_TEST = 0x0C11
	SEPARATE_ATTRIBS = 0x8C8D
	SHADER_BINARY_FORMATS = 0x8DF8
	SHADER_COMPILER = 0x8DFA
	SHADER_IMAGE_ACCESS_BARRIER_BIT = 0x00000020
	SHADER_SOURCE_LENGTH = 0x8B88
	SHADER_STORAGE_BARRIER_BIT = 0x00002000
	SHADER_STORAGE_BLOCK = 0x92E6
	SHADER_STORAGE_BUFFER = 0x90D2
	SHADER_STORAGE_BUFFER_BINDING = 0x90D3
	SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT = 0x90DF
	SHADER_STORAGE_BUFFER_SIZE = 0x90D5
	SHADER_STORAGE_BUFFER_START = 0x90D4
	SHADER_TYPE = 0x8B4F
	SHADING_LANGUAGE_VERSION = 0x8B8C
	SHORT = 0x1402
	SIGNALED = 0x9119
	SIGNED_NORMALIZED = 0x8F9C
	SRC_ALPHA = 0x0302
	SRC_ALPHA_SATURATE = 0x0308
	SRC_COLOR = 0x0300
	SRGB = 0x8C40
	SRGB8 = 0x8C41
	SRGB8_ALPHA8 = 0x8C43
	STATIC_COPY = 0x88E6
	STATIC_DRAW = 0x88E4
	STATIC_READ = 0x88E5
	STENCIL = 0x1802
	STENCIL_ATTACHMENT = 0x8D20
	STENCIL_BACK_FAIL = 0x8801
	STENCIL_BACK_FUNC = 0x8800
	STENCIL_BACK_PASS_DEPTH_FAIL = 0x8802
	STENCIL_BACK_PASS_DEPTH_PASS = 0x8803
	STENCIL_BACK_REF = 0x8CA3
	STENCIL_BACK_VALUE_MASK = 0x8CA4
	STENCIL_BACK_WRITEMASK = 0x8CA5
	STENCIL_BITS = 0x0D57
	STENCIL_BUFFER_BIT = 0x00000400
	STENCIL_CLEAR_VALUE = 0x0B91
	STENCIL_FAIL = 0x0B94
	STENCIL_FUNC = 0x0B92
	STENCIL_INDEX = 0x1901
	STENCIL_INDEX8 = 0x8D48
	STENCIL_PASS_DEPTH_FAIL = 0x0B95
	STENCIL_PASS_DEPTH_PASS = 0x0B96
	STENCIL_REF = 0x0B97
	STENCIL_TEST = 0x0B90
	STENCIL_VALUE_MASK = 0x0B93
	STENCIL_WRITEMASK = 0x0B98
	STREAM_COPY = 0x88E2
	STREAM_DRAW = 0x88E0
	STREAM_READ = 0x88E1
	SUBPIXEL_BITS = 0x0D50
	SYNC_CONDITION = 0x9113
	SYNC_FENCE = 0x9116
	SYNC_FLAGS = 0x9115
	SYNC_FLUSH_COMMANDS_BIT = 0x00000001
	SYNC_GPU_COMMANDS_COMPLETE = 0x9117
	SYNC_STATUS = 0x9114
	TEXTURE = 0x1702
	TEXTURE0 = 0x84C0
	TEXTURE1 = 0x84C1
	TEXTURE10 = 0x84CA
	TEXTURE11 = 0x84CB
	TEXTURE12 = 0x84CC
	TEXTURE13 = 0x84CD
	TEXTURE14 = 0x84CE
	TEXTURE15 = 0x84CF
	TEXTURE16 = 0x84D0
	TEXTURE17 = 0x84D1
	TEXTURE18 = 0x84D2
	TEXTURE19 = 0x84D3
	TEXTURE2 = 0x84C2
	TEXTURE20 = 0x84D4
	TEXTURE21 = 0x84D5
	TEXTURE22 = 0x84D6
	TEXTURE23 = 0x84D7
	TEXTURE24 = 0x84D8
	TEXTURE25 = 0x84D9
	TEXTURE26 = 0x84DA
	TEXTURE27 = 0x84DB
	TEXTURE28 = 0x84DC
	TEXTURE29 = 0x84DD
	TEXTURE3 = 0x84C3
	TEXTURE30 = 0x84DE
	TEXTURE31 = 0x84DF
	TEXTURE4 = 0x84C4
	TEXTURE5 = 0x84C5
	TEXTURE6 = 0x84C6
	TEXTURE7 = 0x84C7
	TEXTURE8 = 0x84C8
	TEXTURE9 = 0x84C9
	TEXTURE_2D = 0x0DE1
	TEXTURE_2D_ARRAY = 0x8C1A
	TEXTURE_2D_MULTISAMPLE = 0x9100
	TEXTURE_3D = 0x806F
	TEXTURE_ALPHA_SIZE = 0x805F
	TEXTURE_ALPHA_TYPE = 0x8C13
	TEXTURE_BASE_LEVEL = 0x813C
	TEXTURE_BINDING_2D = 0x8069
	TEXTURE_BINDING_2D_ARRAY = 0x8C1D
	TEXTURE_BINDING_2D_MULTISAMPLE = 0x9104
	TEXTURE_BINDING_3D = 0x806A
	TEXTURE_BINDING_CUBE_MAP = 0x8514
	TEXTURE_BLUE_SIZE = 0x805E
	TEXTURE_BLUE_TYPE = 0x8C12
	TEXTURE_COMPARE_FUNC = 0x884D
	TEXTURE_COMPARE_MODE = 0x884C
	TEXTURE_COMPRESSED = 0x86A1
	TEXTURE_CUBE_MAP = 0x8513
	TEXTURE_CUBE_MAP_NEGATIVE_X = 0x8516
	TEXTURE_CUBE_MAP_NEGATIVE_Y = 0x8518
	TEXTURE_CUBE_MAP_NEGATIVE_Z = 0x851A
	TEXTURE_CUBE_MAP_POSITIVE_X = 0x8515
	TEXTURE_CUBE_MAP_POSITIVE_Y = 0x8517
	TEXTURE_CUBE_MAP_POSITIVE_Z = 0x8519
	TEXTURE_DEPTH = 0x8071
	TEXTURE_DEPTH_SIZE = 0x884A
	TEXTURE_DEPTH_TYPE = 0x8C16
	TEXTURE_FETCH_BARRIER_BIT = 0x00000008
	TEXTURE_FIXED_SAMPLE_LOCATIONS = 0x9107
	TEXTURE_GREEN_SIZE = 0x805D
	TEXTURE_GREEN_TYPE = 0x8C11
	TEXTURE_HEIGHT = 0x1001
	TEXTURE_IMMUTABLE_FORMAT = 0x912F
	TEXTURE_IMMUTABLE_LEVELS = 0x82DF
	TEXTURE_INTERNAL_FORMAT = 0x1003
	TEXTURE_MAG_FILTER = 0x2800
	TEXTURE_MAX_LEVEL = 0x813D
	TEXTURE_MAX_LOD = 0x813B
	TEXTURE_MIN_FILTER = 0x2801
	TEXTURE_MIN_LOD = 0x813A
	TEXTURE_RED_SIZE = 0x805C
	TEXTURE_RED_TYPE = 0x8C10
	TEXTURE_SAMPLES = 0x9106
	TEXTURE_SHARED_SIZE = 0x8C3F
	TEXTURE_STENCIL_SIZE = 0x88F1
	TEXTURE_SWIZZLE_A = 0x8E45
	TEXTURE_SWIZZLE_B = 0x8E44
	TEXTURE_SWIZZLE_G = 0x8E43
	TEXTURE_SWIZZLE_R = 0x8E42
	TEXTURE_UPDATE_BARRIER_BIT = 0x00000100
	TEXTURE_WIDTH = 0x1000
	TEXTURE_WRAP_R = 0x8072
	TEXTURE_WRAP_S = 0x2802
	TEXTURE_WRAP_T = 0x2803
	TIMEOUT_EXPIRED = 0x911B
	TIMEOUT_IGNORED = 0xFFFFFFFFFFFFFFFF
	TOP_LEVEL_ARRAY_SIZE = 0x930C
	TOP_LEVEL_ARRAY_STRIDE = 0x930D
	TRANSFORM_FEEDBACK = 0x8E22
	TRANSFORM_FEEDBACK_ACTIVE = 0x8E24
	TRANSFORM_FEEDBACK_BARRIER_BIT = 0x00000800
	TRANSFORM_FEEDBACK_BINDING = 0x8E25
	TRANSFORM_FEEDBACK_BUFFER = 0x8C8E
	TRANSFORM_FEEDBACK_BUFFER_BINDING = 0x8C8F
	TRANSFORM_FEEDBACK_BUFFER_MODE = 0x8C7F
	TRANSFORM_FEEDBACK_BUFFER_SIZE = 0x8C85
	TRANSFORM_FEEDBACK_BUFFER_START = 0x8C84
	TRANSFORM_FEEDBACK_PAUSED = 0x8E23
	TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN = 0x8C88
	TRANSFORM_FEEDBACK_VARYING = 0x92F4
	TRANSFORM_FEEDBACK_VARYINGS = 0x8C83
	TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH = 0x8C76
	TRIANGLES = 0x0004
	TRIANGLE_FAN = 0x0006
	TRIANGLE_STRIP = 0x0005
	TRUE = 1
	TYPE = 0x92FA
	UNIFORM = 0x92E1
	UNIFORM_ARRAY_STRIDE = 0x8A3C
	UNIFORM_BARRIER_BIT = 0x00000004
	UNIFORM_BLOCK = 0x92E2
	UNIFORM_BLOCK_ACTIVE_UNIFORMS = 0x8A42
	UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES = 0x8A43
	UNIFORM_BLOCK_BINDING = 0x8A3F
	UNIFORM_BLOCK_DATA_SIZE = 0x8A40
	UNIFORM_BLOCK_INDEX = 0x8A3A
	UNIFORM_BLOCK_NAME_LENGTH = 0x8A41
	UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER = 0x8A46
	UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER = 0x8A44
	UNIFORM_BUFFER = 0x8A11
	UNIFORM_BUFFER_BINDING = 0x8A28
	UNIFORM_BUFFER_OFFSET_ALIGNMENT = 0x8A34
	UNIFORM_BUFFER_SIZE = 0x8A2A
	UNIFORM_BUFFER_START = 0x8A29
	UNIFORM_IS_ROW_MAJOR = 0x8A3E
	UNIFORM_MATRIX_STRIDE = 0x8A3D
	UNIFORM_NAME_LENGTH = 0x8A39
	UNIFORM_OFFSET = 0x8A3B
	UNIFORM_SIZE = 0x8A38
	UNIFORM_TYPE = 0x8A37
	UNPACK_ALIGNMENT = 0x0CF5
	UNPACK_IMAGE_HEIGHT = 0x806E
	UNPACK_ROW_LENGTH = 0x0CF2
	UNPACK_SKIP_IMAGES = 0x806D
	UNPACK_SKIP_PIXELS = 0x0CF4
	UNPACK_SKIP_ROWS = 0x0CF3
	UNSIGNALED = 0x9118
	UNSIGNED_BYTE = 0x1401
	UNSIGNED_INT = 0x1405
	UNSIGNED_INT_10F_11F_11F_REV = 0x8C3B
	UNSIGNED_INT_24_8 = 0x84FA
	UNSIGNED_INT_2_10_10_10_REV = 0x8368
	UNSIGNED_INT_5_9_9_9_REV = 0x8C3E
	UNSIGNED_INT_ATOMIC_COUNTER = 0x92DB
	UNSIGNED_INT_IMAGE_2D = 0x9063
	UNSIGNED_INT_IMAGE_2D_ARRAY = 0x9069
	UNSIGNED_INT_IMAGE_3D = 0x9064
	UNSIGNED_INT_IMAGE_CUBE = 0x9066
	UNSIGNED_INT_SAMPLER_2D = 0x8DD2
	UNSIGNED_INT_SAMPLER_2D_ARRAY = 0x8DD7
	UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE = 0x910A
	UNSIGNED_INT_SAMPLER_3D = 0x8DD3
	UNSIGNED_INT_SAMPLER_CUBE = 0x8DD4
	UNSIGNED_INT_VEC2 = 0x8DC6
	UNSIGNED_INT_VEC3 = 0x8DC7
	UNSIGNED_INT_VEC4 = 0x8DC8
	UNSIGNED_NORMALIZED = 0x8C17
	UNSIGNED_SHORT = 0x1403
	UNSIGNED_SHORT_4_4_4_4 = 0x8033
	UNSIGNED_SHORT_5_5_5_1 = 0x8034
	UNSIGNED_SHORT_5_6_5 = 0x8363
	VALIDATE_STATUS = 0x8B83
	VENDOR = 0x1F00
	VERSION = 0x1F02
	VERTEX_ARRAY_BINDING = 0x85B5
	VERTEX_ATTRIB_ARRAY_BARRIER_BIT = 0x00000001
	VERTEX_ATTRIB_ARRAY_BUFFER_BINDING = 0x889F
	VERTEX_ATTRIB_ARRAY_DIVISOR = 0x88FE
	VERTEX_ATTRIB_ARRAY_ENABLED = 0x8622
	VERTEX_ATTRIB_ARRAY_INTEGER = 0x88FD
	VERTEX_ATTRIB_ARRAY_NORMALIZED = 0x886A
	VERTEX_ATTRIB_ARRAY_POINTER = 0x8645
	VERTEX_ATTRIB_ARRAY_SIZE = 0x8623
	VERTEX_ATTRIB_ARRAY_STRIDE = 0x8624
	VERTEX_ATTRIB_ARRAY_TYPE = 0x8625
	VERTEX_ATTRIB_BINDING = 0x82D4
	VERTEX_ATTRIB_RELATIVE_OFFSET = 0x82D5
	VERTEX_BINDING_BUFFER = 0x8F4F
	VERTEX_BINDING_DIVISOR = 0x82D6
	VERTEX_BINDING_OFFSET = 0x82D7
	VERTEX_BINDING_STRIDE = 0x82D8
	VERTEX_SHADER = 0x8B31
	VERTEX_SHADER_BIT = 0x00000001
	VIEWPORT = 0x0BA2
	WAIT_FAILED = 0x911D
	WRITE_ONLY = 0x88B9
	ZERO = 0
)

// -----------------------------------------------------------------------------
// Functions
// -----------------------------------------------------------------------------

func ActiveShaderProgram(pipeline uint32, program uint32) { gpActiveShaderProgram(pipeline, program) }
func ActiveTexture(texture uint32) { gpActiveTexture(texture) }
func AttachShader(program uint32, shader uint32) { gpAttachShader(program, shader) }
func BeginQuery(target uint32, id uint32) { gpBeginQuery(target, id) }
func BeginTransformFeedback(primitiveMode uint32) { gpBeginTransformFeedback(primitiveMode) }
func BindAttribLocation(program uint32, index uint32, name *uint8) { gpBindAttribLocation(program, index, name) }
func BindBuffer(target uint32, buffer uint32) { gpBindBuffer(target, buffer) }
func BindBufferBase(target uint32, index uint32, buffer uint32) { gpBindBufferBase(target, index, buffer) }
func BindBufferRange(target uint32, index uint32, buffer uint32, offset int, size int) { gpBindBufferRange(target, index, buffer, offset, size) }
func BindFramebuffer(target uint32, framebuffer uint32) { gpBindFramebuffer(target, framebuffer) }
func BindImageTexture(unit uint32, texture uint32, level int32, layered bool, layer int32, access uint32, format uint32) { gpBindImageTexture(unit, texture, level, layered, layer, access, format) }
func BindProgramPipeline(pipeline uint32) { gpBindProgramPipeline(pipeline) }
func BindRenderbuffer(target uint32, renderbuffer uint32) { gpBindRenderbuffer(target, renderbuffer) }
func BindSampler(unit uint32, sampler uint32) { gpBindSampler(unit, sampler) }
func BindTexture(target uint32, texture uint32) { gpBindTexture(target, texture) }
func BindTransformFeedback(target uint32, id uint32) { gpBindTransformFeedback(target, id) }
func BindVertexArray(array uint32) { gpBindVertexArray(array) }
func BindVertexBuffer(bindingindex uint32, buffer uint32, offset int, stride int32) { gpBindVertexBuffer(bindingindex, buffer, offset, stride) }
func BlendColor(red float32, green float32, blue float32, alpha float32) { gpBlendColor(red, green, blue, alpha) }
func BlendEquation(mode uint32) { gpBlendEquation(mode) }
func BlendEquationSeparate(modeRGB uint32, modeAlpha uint32) { gpBlendEquationSeparate(modeRGB, modeAlpha) }
func BlendFunc(sfactor uint32, dfactor uint32) { gpBlendFunc(sfactor, dfactor) }
func BlendFuncSeparate(sfactorRGB uint32, dfactorRGB uint32, sfactorAlpha uint32, dfactorAlpha uint32) { gpBlendFuncSeparate(sfactorRGB, dfactorRGB, sfactorAlpha, dfactorAlpha) }
func BlitFramebuffer(srcX0 int32, srcY0 int32, srcX1 int32, srcY1 int32, dstX0 int32, dstY0 int32, dstX1 int32, dstY1 int32, mask uint32, filter uint32) { gpBlitFramebuffer(srcX0, srcY0, srcX1, srcY1, dstX0, dstY0, dstX1, dstY1, mask, filter) }
func BufferData(target uint32, size int, data unsafe.Pointer, usage uint32) { gpBufferData(target, size, data, usage) }
func BufferSubData(target uint32, offset int, size int, data unsafe.Pointer) { gpBufferSubData(target, offset, size, data) }
func CheckFramebufferStatus(target uint32) uint32 { return gpCheckFramebufferStatus(target) }
func Clear(mask uint32) { gpClear(mask) }
func ClearBufferfi(buffer uint32, drawbuffer int32, depth float32, stencil int32) { gpClearBufferfi(buffer, drawbuffer, depth, stencil) }
func ClearBufferfv(buffer uint32, drawbuffer int32, value *float32) { gpClearBufferfv(buffer, drawbuffer, value) }
func ClearBufferiv(buffer uint32, drawbuffer int32, value *int32) { gpClearBufferiv(buffer, drawbuffer, value) }
func ClearBufferuiv(buffer uint32, drawbuffer int32, value *uint32) { gpClearBufferuiv(buffer, drawbuffer, value) }
func ClearColor(red float32, green float32, blue float32, alpha float32) { gpClearColor(red, green, blue, alpha) }
func ClearDepthf(d float32) { gpClearDepthf(d) }
func ClearStencil(s int32) { gpClearStencil(s) }
func ClientWaitSync(sync uintptr, flags uint32, timeout uint64) uint32 { return gpClientWaitSync(sync, flags, timeout) }
func ColorMask(red bool, green bool, blue bool, alpha bool) { gpColorMask(red, green, blue, alpha) }
func CompileShader(shader uint32) { gpCompileShader(shader) }
func CompressedTexImage2D(target uint32, level int32, internalformat uint32, width int32, height int32, border int32, imageSize int32, data unsafe.Pointer) { gpCompressedTexImage2D(target, level, internalformat, width, height, border, imageSize, data) }
func CompressedTexImage3D(target uint32, level int32, internalformat uint32, width int32, height int32, depth int32, border int32, imageSize int32, data unsafe.Pointer) { gpCompressedTexImage3D(target, level, internalformat, width, height, depth, border, imageSize, data) }
func CompressedTexSubImage2D(target uint32, level int32, xoffset int32, yoffset int32, width int32, height int32, format uint32, imageSize int32, data unsafe.Pointer) { gpCompressedTexSubImage2D(target, level, xoffset, yoffset, width, height, format, imageSize, data) }
func CompressedTexSubImage3D(target uint32, level int32, xoffset int32, yoffset int32, zoffset int32, width int32, height int32, depth int32, format uint32, imageSize int32, data unsafe.Pointer) { gpCompressedTexSubImage3D(target, level, xoffset, yoffset, zoffset, width, height, depth, format, imageSize, data) }
func CopyBufferSubData(readTarget uint32, writeTarget uint32, readOffset int, writeOffset int, size int) { gpCopyBufferSubData(readTarget, writeTarget, readOffset, writeOffset, size) }
func CopyTexImage2D(target uint32, level int32, internalformat uint32, x int32, y int32, width int32, height int32, border int32) { gpCopyTexImage2D(target, level, internalformat, x, y, width, height, border) }
func CopyTexSubImage2D(target uint32, level int32, xoffset int32, yoffset int32, x int32, y int32, width int32, height int32) { gpCopyTexSubImage2D(target, level, xoffset, yoffset, x, y, width, height) }
func CopyTexSubImage3D(target uint32, level int32, xoffset int32, yoffset int32, zoffset int32, x int32, y int32, width int32, height int32) { gpCopyTexSubImage3D(target, level, xoffset, yoffset, zoffset, x, y, width, height) }
func CreateProgram() uint32 { return gpCreateProgram() }
func CreateShader(xtype uint32) uint32 { return gpCreateShader(xtype) }
func CreateShaderProgramv(xtype uint32, count int32, strings **uint8) uint32 { return gpCreateShaderProgramv(xtype, count, strings) }
func CullFace(mode uint32) { gpCullFace(mode) }
func DeleteBuffers(n int32, buffers *uint32) { gpDeleteBuffers(n, buffers) }
func DeleteFramebuffers(n int32, framebuffers *uint32) { gpDeleteFramebuffers(n, framebuffers) }
func DeleteProgram(program uint32) { gpDeleteProgram(program) }
func DeleteProgramPipelines(n int32, pipelines *uint32) { gpDeleteProgramPipelines(n, pipelines) }
func DeleteQueries(n int32, ids *uint32) { gpDeleteQueries(n, ids) }
func DeleteRenderbuffers(n int32, renderbuffers *uint32) { gpDeleteRenderbuffers(n, renderbuffers) }
func DeleteSamplers(count int32, samplers *uint32) { gpDeleteSamplers(count, samplers) }
func DeleteShader(shader uint32) { gpDeleteShader(shader) }
func DeleteSync(sync uintptr) { gpDeleteSync(sync) }
func DeleteTextures(n int32, textures *uint32) { gpDeleteTextures(n, textures) }
func DeleteTransformFeedbacks(n int32, ids *uint32) { gpDeleteTransformFeedbacks(n, ids) }
func DeleteVertexArrays(n int32, arrays *uint32) { gpDeleteVertexArrays(n, arrays) }
func DepthFunc(xfunc uint32) { gpDepthFunc(xfunc) }
func DepthMask(flag bool) { gpDepthMask(flag) }
func DepthRangef(n float32, f float32) { gpDepthRangef(n, f) }
func DetachShader(program uint32, shader uint32) { gpDetachShader(program, shader) }
func Disable(xcap uint32) { gpDisable(xcap) }
func DisableVertexAttribArray(index uint32) { gpDisableVertexAttribArray(index) }
func DispatchCompute(num_groups_x uint32, num_groups_y uint32, num_groups_z uint32) { gpDispatchCompute(num_groups_x, num_groups_y, num_groups_z) }
func DispatchComputeIndirect(indirect int) { gpDispatchComputeIndirect(indirect) }
func DrawArrays(mode uint32, first int32, count int32) { gpDrawArrays(mode, first, count) }
func DrawArraysIndirect(mode uint32, indirect unsafe.Pointer) { gpDrawArraysIndirect(mode, indirect) }
func DrawArraysInstanced(mode uint32, first int32, count int32, instancecount int32) { gpDrawArraysInstanced(mode, first, count, instancecount) }
func DrawBuffers(n int32, bufs *uint32) { gpDrawBuffers(n, bufs) }
func DrawElements(mode uint32, count int32, xtype uint32, indices unsafe.Pointer) { gpDrawElements(mode, count, xtype, indices) }
func DrawElementsIndirect(mode uint32, xtype uint32, indirect unsafe.Pointer) { gpDrawElementsIndirect(mode, xtype, indirect) }
func DrawElementsInstanced(mode uint32, count int32, xtype uint32, indices unsafe.Pointer, instancecount int32) { gpDrawElementsInstanced(mode, count, xtype, indices, instancecount) }
func DrawRangeElements(mode uint32, start uint32, end uint32, count int32, xtype uint32, indices unsafe.Pointer) { gpDrawRangeElements(mode, start, end, count, xtype, indices) }
func Enable(xcap uint32) { gpEnable(xcap) }
func EnableVertexAttribArray(index uint32) { gpEnableVertexAttribArray(index) }
func EndQuery(target uint32) { gpEndQuery(target) }
func EndTransformFeedback() { gpEndTransformFeedback() }
func FenceSync(condition uint32, flags uint32) uintptr { return gpFenceSync(condition, flags) }
func Finish() { gpFinish() }
func Flush() { gpFlush() }
func FlushMappedBufferRange(target uint32, offset int, length int) { gpFlushMappedBufferRange(target, offset, length) }
func FramebufferParameteri(target uint32, pname uint32, param int32) { gpFramebufferParameteri(target, pname, param) }
func FramebufferRenderbuffer(target uint32, attachment uint32, renderbuffertarget uint32, renderbuffer uint32) { gpFramebufferRenderbuffer(target, attachment, renderbuffertarget, renderbuffer) }
func FramebufferTexture2D(target uint32, attachment uint32, textarget uint32, texture uint32, level int32) { gpFramebufferTexture2D(target, attachment, textarget, texture, level) }
func FramebufferTextureLayer(target uint32, attachment uint32, texture uint32, level int32, layer int32) { gpFramebufferTextureLayer(target, attachment, texture, level, layer) }
func FrontFace(mode uint32) { gpFrontFace(mode) }
func GenBuffers(n int32, buffers *uint32) { gpGenBuffers(n, buffers) }
func GenFramebuffers(n int32, framebuffers *uint32) { gpGenFramebuffers(n, framebuffers) }
func GenProgramPipelines(n int32, pipelines *uint32) { gpGenProgramPipelines(n, pipelines) }
func GenQueries(n int32, ids *uint32) { gpGenQueries(n, ids) }
func GenRenderbuffers(n int32, renderbuffers *uint32) { gpGenRenderbuffers(n, renderbuffers) }
func GenSamplers(count int32, samplers *uint32) { gpGenSamplers(count, samplers) }
func GenTextures(n int32, textures *uint32) { gpGenTextures(n, textures) }
func GenTransformFeedbacks(n int32, ids *uint32) { gpGenTransformFeedbacks(n, ids) }
func GenVertexArrays(n int32, arrays *uint32) { gpGenVertexArrays(n, arrays) }
func GenerateMipmap(target uint32) { gpGenerateMipmap(target) }
func GetActiveAttrib(program uint32, index uint32, bufSize int32, length *int32, size *int32, xtype *uint32, name *uint8) { gpGetActiveAttrib(program, index, bufSize, length, size, xtype, name) }
func GetActiveUniform(program uint32, index uint32, bufSize int32, length *int32, size *int32, xtype *uint32, name *uint8) { gpGetActiveUniform(program, index, bufSize, length, size, xtype, name) }
func GetActiveUniformBlockName(program uint32, uniformBlockIndex uint32, bufSize int32, length *int32, uniformBlockName *uint8) { gpGetActiveUniformBlockName(program, uniformBlockIndex, bufSize, length, uniformBlockName) }
func GetActiveUniformBlockiv(program uint32, uniformBlockIndex uint32, pname uint32, params *int32) { gpGetActiveUniformBlockiv(program, uniformBlockIndex, pname, params) }
func GetActiveUniformsiv(program uint32, uniformCount int32, uniformIndices *uint32, pname uint32, params *int32) { gpGetActiveUniformsiv(program, uniformCount, uniformIndices, pname, params) }
func GetAttachedShaders(program uint32, maxCount int32, count *int32, shaders *uint32) { gpGetAttachedShaders(program, maxCount, count, shaders) }
func GetAttribLocation(program uint32, name *uint8) int32 { return gpGetAttribLocation(program, name) }
func GetBooleani_v(target uint32, index uint32, data *uint8) { gpGetBooleani_v(target, index, data) }
func GetBooleanv(pname uint32, data *uint8) { gpGetBooleanv(pname, data) }
func GetBufferParameteri64v(target uint32, pname uint32, params *int64) { gpGetBufferParameteri64v(target, pname, params) }
func GetBufferParameteriv(target uint32, pname uint32, params *int32) { gpGetBufferParameteriv(target, pname, params) }
func GetBufferPointerv(target uint32, pname uint32, params unsafe.Pointer) { gpGetBufferPointerv(target, pname, params) }
func GetError() uint32 { return gpGetError() }
func GetFloatv(pname uint32, data *float32) { gpGetFloatv(pname, data) }
func GetFragDataLocation(program uint32, name *uint8) int32 { return gpGetFragDataLocation(program, name) }
func GetFramebufferAttachmentParameteriv(target uint32, attachment uint32, pname uint32, params *int32) { gpGetFramebufferAttachmentParameteriv(target, attachment, pname, params) }
func GetFramebufferParameteriv(target uint32, pname uint32, params *int32) { gpGetFramebufferParameteriv(target, pname, params) }
func GetInteger64i_v(target uint32, index uint32, data *int64) { gpGetInteger64i_v(target, index, data) }
func GetInteger64v(pname uint32, data *int64) { gpGetInteger64v(pname, data) }
func GetIntegeri_v(target uint32, index uint32, data *int32) { gpGetIntegeri_v(target, index, data) }
func GetIntegerv(pname uint32, data *int32) { gpGetIntegerv(pname, data) }
func GetInternalformativ(target uint32, internalformat uint32, pname uint32, count int32, params *int32) { gpGetInternalformativ(target, internalformat, pname, count, params) }
func GetMultisamplefv(pname uint32, index uint32, val *float32) { gpGetMultisamplefv(pname, index, val) }
func GetProgramBinary(program uint32, bufSize int32, length *int32, binaryFormat *uint32, binary unsafe.Pointer) { gpGetProgramBinary(program, bufSize, length, binaryFormat, binary) }
func GetProgramInfoLog(program uint32, bufSize int32, length *int32, infoLog *uint8) { gpGetProgramInfoLog(program, bufSize, length, infoLog) }
func GetProgramInterfaceiv(program uint32, programInterface uint32, pname uint32, params *int32) { gpGetProgramInterfaceiv(program, programInterface, pname, params) }
func GetProgramPipelineInfoLog(pipeline uint32, bufSize int32, length *int32, infoLog *uint8) { gpGetProgramPipelineInfoLog(pipeline, bufSize, length, infoLog) }
func GetProgramPipelineiv(pipeline uint32, pname uint32, params *int32) { gpGetProgramPipelineiv(pipeline, pname, params) }
func GetProgramResourceIndex(program uint32, programInterface uint32, name *uint8) uint32 { return gpGetProgramResourceIndex(program, programInterface, name) }
func GetProgramResourceLocation(program uint32, programInterface uint32, name *uint8) int32 { return gpGetProgramResourceLocation(program, programInterface, name) }
func GetProgramResourceName(program uint32, programInterface uint32, index uint32, bufSize int32, length *int32, name *uint8) { gpGetProgramResourceName(program, programInterface, index, bufSize, length, name) }
func GetProgramResourceiv(program uint32, programInterface uint32, index uint32, propCount int32, props *uint32, count int32, length *int32, params *int32) { gpGetProgramResourceiv(program, programInterface, index, propCount, props, count, length, params) }
func GetProgramiv(program uint32, pname uint32, params *int32) { gpGetProgramiv(program, pname, params) }
func GetQueryObjectuiv(id uint32, pname uint32, params *uint32) { gpGetQueryObjectuiv(id, pname, params) }
func GetQueryiv(target uint32, pname uint32, params *int32) { gpGetQueryiv(target, pname, params) }
func GetRenderbufferParameteriv(target uint32, pname uint32, params *int32) { gpGetRenderbufferParameteriv(target, pname, params) }
func GetSamplerParameterfv(sampler uint32, pname uint32, params *float32) { gpGetSamplerParameterfv(sampler, pname, params) }
func GetSamplerParameteriv(sampler uint32, pname uint32, params *int32) { gpGetSamplerParameteriv(sampler, pname, params) }
func GetShaderInfoLog(shader uint32, bufSize int32, length *int32, infoLog *uint8) { gpGetShaderInfoLog(shader, bufSize, length, infoLog) }
func GetShaderPrecisionFormat(shadertype uint32, precisiontype uint32, xrange *int32, precision *int32) { gpGetShaderPrecisionFormat(shadertype, precisiontype, xrange, precision) }
func GetShaderSource(shader uint32, bufSize int32, length *int32, source *uint8) { gpGetShaderSource(shader, bufSize, length, source) }
func GetShaderiv(shader uint32, pname uint32, params *int32) { gpGetShaderiv(shader, pname, params) }
func GetString(name uint32) *uint8 { return gpGetString(name) }
func GetStringi(name uint32, index uint32) *uint8 { return gpGetStringi(name, index) }
func GetSynciv(sync uintptr, pname uint32, count int32, length *int32, values *int32) { gpGetSynciv(sync, pname, count, length, values) }
func GetTexLevelParameterfv(target uint32, level int32, pname uint32, params *float32) { gpGetTexLevelParameterfv(target, level, pname, params) }
func GetTexLevelParameteriv(target uint32, level int32, pname uint32, params *int32) { gpGetTexLevelParameteriv(target, level, pname, params) }
func GetTexParameterfv(target uint32, pname uint32, params *float32) { gpGetTexParameterfv(target, pname, params) }
func GetTexParameteriv(target uint32, pname uint32, params *int32) { gpGetTexParameteriv(target, pname, params) }
func GetTransformFeedbackVarying(program uint32, index uint32, bufSize int32, length *int32, size *int32, xtype *uint32, name *uint8) { gpGetTransformFeedbackVarying(program, index, bufSize, length, size, xtype, name) }
func GetUniformBlockIndex(program uint32, uniformBlockName *uint8) uint32 { return gpGetUniformBlockIndex(program, uniformBlockName) }
func GetUniformIndices(program uint32, uniformCount int32, uniformNames **uint8, uniformIndices *uint32) { gpGetUniformIndices(program, uniformCount, uniformNames, uniformIndices) }
func GetUniformLocation(program uint32, name *uint8) int32 { return gpGetUniformLocation(program, name) }
func GetUniformfv(program uint32, location int32, params *float32) { gpGetUniformfv(program, location, params) }
func GetUniformiv(program uint32, location int32, params *int32) { gpGetUniformiv(program, location, params) }
func GetUniformuiv(program uint32, location int32, params *uint32) { gpGetUniformuiv(program, location, params) }
func GetVertexAttribIiv(index uint32, pname uint32, params *int32) { gpGetVertexAttribIiv(index, pname, params) }
func GetVertexAttribIuiv(index uint32, pname uint32, params *uint32) { gpGetVertexAttribIuiv(index, pname, params) }
func GetVertexAttribPointerv(index uint32, pname uint32, pointer unsafe.Pointer) { gpGetVertexAttribPointerv(index, pname, pointer) }
func GetVertexAttribfv(index uint32, pname uint32, params *float32) { gpGetVertexAttribfv(index, pname, params) }
func GetVertexAttribiv(index uint32, pname uint32, params *int32) { gpGetVertexAttribiv(index, pname, params) }
func Hint(target uint32, mode uint32) { gpHint(target, mode) }
func InvalidateFramebuffer(target uint32, numAttachments int32, attachments *uint32) { gpInvalidateFramebuffer(target, numAttachments, attachments) }
func InvalidateSubFramebuffer(target uint32, numAttachments int32, attachments *uint32, x int32, y int32, width int32, height int32) { gpInvalidateSubFramebuffer(target, numAttachments, attachments, x, y, width, height) }
func IsBuffer(buffer uint32) bool { return gpIsBuffer(buffer) }
func IsEnabled(xcap uint32) bool { return gpIsEnabled(xcap) }
func IsFramebuffer(framebuffer uint32) bool { return gpIsFramebuffer(framebuffer) }
func IsProgram(program uint32) bool { return gpIsProgram(program) }
func IsProgramPipeline(pipeline uint32) bool { return gpIsProgramPipeline(pipeline) }
func IsQuery(id uint32) bool { return gpIsQuery(id) }
func IsRenderbuffer(renderbuffer uint32) bool { return gpIsRenderbuffer(renderbuffer) }
func IsSampler(sampler uint32) bool { return gpIsSampler(sampler) }
func IsShader(shader uint32) bool { return gpIsShader(shader) }
func IsSync(sync uintptr) bool { return gpIsSync(sync) }
func IsTexture(texture uint32) bool { return gpIsTexture(texture) }
func IsTransformFeedback(id uint32) bool { return gpIsTransformFeedback(id) }
func IsVertexArray(array uint32) bool { return gpIsVertexArray(array) }
func LineWidth(width float32) { gpLineWidth(width) }
func LinkProgram(program uint32) { gpLinkProgram(program) }
func MapBufferRange(target uint32, offset int, length int, access uint32) unsafe.Pointer { return gpMapBufferRange(target, offset, length, access) }
func MemoryBarrier(barriers uint32) { gpMemoryBarrier(barriers) }
func MemoryBarrierByRegion(barriers uint32) { gpMemoryBarrierByRegion(barriers) }
func PauseTransformFeedback() { gpPauseTransformFeedback() }
func PixelStorei(pname uint32, param int32) { gpPixelStorei(pname, param) }
func PolygonOffset(factor float32, units float32) { gpPolygonOffset(factor, units) }
func ProgramBinary(program uint32, binaryFormat uint32, binary unsafe.Pointer, length int32) { gpProgramBinary(program, binaryFormat, binary, length) }
func ProgramParameteri(program uint32, pname uint32, value int32) { gpProgramParameteri(program, pname, value) }
func ProgramUniform1f(program uint32, location int32, v0 float32) { gpProgramUniform1f(program, location, v0) }
func ProgramUniform1fv(program uint32, location int32, count int32, value *float32) { gpProgramUniform1fv(program, location, count, value) }
func ProgramUniform1i(program uint32, location int32, v0 int32) { gpProgramUniform1i(program, location, v0) }
func ProgramUniform1iv(program uint32, location int32, count int32, value *int32) { gpProgramUniform1iv(program, location, count, value) }
func ProgramUniform1ui(program uint32, location int32, v0 uint32) { gpProgramUniform1ui(program, location, v0) }
func ProgramUniform1uiv(program uint32, location int32, count int32, value *uint32) { gpProgramUniform1uiv(program, location, count, value) }
func ProgramUniform2f(program uint32, location int32, v0 float32, v1 float32) { gpProgramUniform2f(program, location, v0, v1) }
func ProgramUniform2fv(program uint32, location int32, count int32, value *float32) { gpProgramUniform2fv(program, location, count, value) }
func ProgramUniform2i(program uint32, location int32, v0 int32, v1 int32) { gpProgramUniform2i(program, location, v0, v1) }
func ProgramUniform2iv(program uint32, location int32, count int32, value *int32) { gpProgramUniform2iv(program, location, count, value) }
func ProgramUniform2ui(program uint32, location int32, v0 uint32, v1 uint32) { gpProgramUniform2ui(program, location, v0, v1) }
func ProgramUniform2uiv(program uint32, location int32, count int32, value *uint32) { gpProgramUniform2uiv(program, location, count, value) }
func ProgramUniform3f(program uint32, location int32, v0 float32, v1 float32, v2 float32) { gpProgramUniform3f(program, location, v0, v1, v2) }
func ProgramUniform3fv(program uint32, location int32, count int32, value *float32) { gpProgramUniform3fv(program, location, count, value) }
func ProgramUniform3i(program uint32, location int32, v0 int32, v1 int32, v2 int32) { gpProgramUniform3i(program, location, v0, v1, v2) }
func ProgramUniform3iv(program uint32, location int32, count int32, value *int32) { gpProgramUniform3iv(program, location, count, value) }
func ProgramUniform3ui(program uint32, location int32, v0 uint32, v1 uint32, v2 uint32) { gpProgramUniform3ui(program, location, v0, v1, v2) }
func ProgramUniform3uiv(program uint32, location int32, count int32, value *uint32) { gpProgramUniform3uiv(program, location, count, value) }
func ProgramUniform4f(program uint32, location int32, v0 float32, v1 float32, v2 float32, v3 float32) { gpProgramUniform4f(program, location, v0, v1, v2, v3) }
func ProgramUniform4fv(program uint32, location int32, count int32, value *float32) { gpProgramUniform4fv(program, location, count, value) }
func ProgramUniform4i(program uint32, location int32, v0 int32, v1 int32, v2 int32, v3 int32) { gpProgramUniform4i(program, location, v0, v1, v2, v3) }
func ProgramUniform4iv(program uint32, location int32, count int32, value *int32) { gpProgramUniform4iv(program, location, count, value) }
func ProgramUniform4ui(program uint32, location int32, v0 uint32, v1 uint32, v2 uint32, v3 uint32) { gpProgramUniform4ui(program, location, v0, v1, v2, v3) }
func ProgramUniform4uiv(program uint32, location int32, count int32, value *uint32) { gpProgramUniform4uiv(program, location, count, value) }
func ProgramUniformMatrix2fv(program uint32, location int32, count int32, transpose bool, value *float32) { gpProgramUniformMatrix2fv(program, location, count, transpose, value) }
func ProgramUniformMatrix2x3fv(program uint32, location int32, count int32, transpose bool, value *float32) { gpProgramUniformMatrix2x3fv(program, location, count, transpose, value) }
func ProgramUniformMatrix2x4fv(program uint32, location int32, count int32, transpose bool, value *float32) { gpProgramUniformMatrix2x4fv(program, location, count, transpose, value) }
func ProgramUniformMatrix3fv(program uint32, location int32, count int32, transpose bool, value *float32) { gpProgramUniformMatrix3fv(program, location, count, transpose, value) }
func ProgramUniformMatrix3x2fv(program uint32, location int32, count int32, transpose bool, value *float32) { gpProgramUniformMatrix3x2fv(program, location, count, transpose, value) }
func ProgramUniformMatrix3x4fv(program uint32, location int32, count int32, transpose bool, value *float32) { gpProgramUniformMatrix3x4fv(program, location, count, transpose, value) }
func ProgramUniformMatrix4fv(program uint32, location int32, count int32, transpose bool, value *float32) { gpProgramUniformMatrix4fv(program, location, count, transpose, value) }
func ProgramUniformMatrix4x2fv(program uint32, location int32, count int32, transpose bool, value *float32) { gpProgramUniformMatrix4x2fv(program, location, count, transpose, value) }
func ProgramUniformMatrix4x3fv(program uint32, location int32, count int32, transpose bool, value *float32) { gpProgramUniformMatrix4x3fv(program, location, count, transpose, value) }
func ReadBuffer(src uint32) { gpReadBuffer(src) }
func ReadPixels(x int32, y int32, width int32, height int32, format uint32, xtype uint32, pixels unsafe.Pointer) { gpReadPixels(x, y, width, height, format, xtype, pixels) }
func ReleaseShaderCompiler() { gpReleaseShaderCompiler() }
func RenderbufferStorage(target uint32, internalformat uint32, width int32, height int32) { gpRenderbufferStorage(target, internalformat, width, height) }
func RenderbufferStorageMultisample(target uint32, samples int32, internalformat uint32, width int32, height int32) { gpRenderbufferStorageMultisample(target, samples, internalformat, width, height) }
func ResumeTransformFeedback() { gpResumeTransformFeedback() }
func SampleCoverage(value float32, invert bool) { gpSampleCoverage(value, invert) }
func SampleMaski(maskNumber uint32, mask uint32) { gpSampleMaski(maskNumber, mask) }
func SamplerParameterf(sampler uint32, pname uint32, param float32) { gpSamplerParameterf(sampler, pname, param) }
func SamplerParameterfv(sampler uint32, pname uint32, param *float32) { gpSamplerParameterfv(sampler, pname, param) }
func SamplerParameteri(sampler uint32, pname uint32, param int32) { gpSamplerParameteri(sampler, pname, param) }
func SamplerParameteriv(sampler uint32, pname uint32, param *int32) { gpSamplerParameteriv(sampler, pname, param) }
func Scissor(x int32, y int32, width int32, height int32) { gpScissor(x, y, width, height) }
func ShaderBinary(count int32, shaders *uint32, binaryFormat uint32, binary unsafe.Pointer, length int32) { gpShaderBinary(count, shaders, binaryFormat, binary, length) }
func ShaderSource(shader uint32, count int32, xstring **uint8, length *int32) { gpShaderSource(shader, count, xstring, length) }
func StencilFunc(xfunc uint32, ref int32, mask uint32) { gpStencilFunc(xfunc, ref, mask) }
func StencilFuncSeparate(face uint32, xfunc uint32, ref int32, mask uint32) { gpStencilFuncSeparate(face, xfunc, ref, mask) }
func StencilMask(mask uint32) { gpStencilMask(mask) }
func StencilMaskSeparate(face uint32, mask uint32) { gpStencilMaskSeparate(face, mask) }
func StencilOp(fail uint32, zfail uint32, zpass uint32) { gpStencilOp(fail, zfail, zpass) }
func StencilOpSeparate(face uint32, sfail uint32, dpfail uint32, dppass uint32) { gpStencilOpSeparate(face, sfail, dpfail, dppass) }
func TexImage2D(target uint32, level int32, internalformat int32, width int32, height int32, border int32, format uint32, xtype uint32, pixels unsafe.Pointer) { gpTexImage2D(target, level, internalformat, width, height, border, format, xtype, pixels) }
func TexImage3D(target uint32, level int32, internalformat int32, width int32, height int32, depth int32, border int32, format uint32, xtype uint32, pixels unsafe.Pointer) { gpTexImage3D(target, level, internalformat, width, height, depth, border, format, xtype, pixels) }
func TexParameterf(target uint32, pname uint32, param float32) { gpTexParameterf(target, pname, param) }
func TexParameterfv(target uint32, pname uint32, params *float32) { gpTexParameterfv(target, pname, params) }
func TexParameteri(target uint32, pname uint32, param int32) { gpTexParameteri(target, pname, param) }
func TexParameteriv(target uint32, pname uint32, params *int32) { gpTexParameteriv(target, pname, params) }
func TexStorage2D(target uint32, levels int32, internalformat uint32, width int32, height int32) { gpTexStorage2D(target, levels, internalformat, width, height) }
func TexStorage2DMultisample(target uint32, samples int32, internalformat uint32, width int32, height int32, fixedsamplelocations bool) { gpTexStorage2DMultisample(target, samples, internalformat, width, height, fixedsamplelocations) }
func TexStorage3D(target uint32, levels int32, internalformat uint32, width int32, height int32, depth int32) { gpTexStorage3D(target, levels, internalformat, width, height, depth) }
func TexSubImage2D(target uint32, level int32, xoffset int32, yoffset int32, width int32, height int32, format uint32, xtype uint32, pixels unsafe.Pointer) { gpTexSubImage2D(target, level, xoffset, yoffset, width, height, format, xtype, pixels) }
func TexSubImage3D(target uint32, level int32, xoffset int32, yoffset int32, zoffset int32, width int32, height int32, depth int32, format uint32, xtype uint32, pixels unsafe.Pointer) { gpTexSubImage3D(target, level, xoffset, yoffset, zoffset, width, height, depth, format, xtype, pixels) }
func TransformFeedbackVaryings(program uint32, count int32, varyings **uint8, bufferMode uint32) { gpTransformFeedbackVaryings(program, count, varyings, bufferMode) }
func Uniform1f(location int32, v0 float32) { gpUniform1f(location, v0) }
func Uniform1fv(location int32, count int32, value *float32) { gpUniform1fv(location, count, value) }
func Uniform1i(location int32, v0 int32) { gpUniform1i(location, v0) }
func Uniform1iv(location int32, count int32, value *int32) { gpUniform1iv(location, count, value) }
func Uniform1ui(location int32, v0 uint32) { gpUniform1ui(location, v0) }
func Uniform1uiv(location int32, count int32, value *uint32) { gpUniform1uiv(location, count, value) }
func Uniform2f(location int32, v0 float32, v1 float32) { gpUniform2f(location, v0, v1) }
func Uniform2fv(location int32, count int32, value *float32) { gpUniform2fv(location, count, value) }
func Uniform2i(location int32, v0 int32, v1 int32) { gpUniform2i(location, v0, v1) }
func Uniform2iv(location int32, count int32, value *int32) { gpUniform2iv(location, count, value) }
func Uniform2ui(location int32, v0 uint32, v1 uint32) { gpUniform2ui(location, v0, v1) }
func Uniform2uiv(location int32, count int32, value *uint32) { gpUniform2uiv(location, count, value) }
func Uniform3f(location int32, v0 float32, v1 float32, v2 float32) { gpUniform3f(location, v0, v1, v2) }
func Uniform3fv(location int32, count int32, value *float32) { gpUniform3fv(location, count, value) }
func Uniform3i(location int32, v0 int32, v1 int32, v2 int32) { gpUniform3i(location, v0, v1, v2) }
func Uniform3iv(location int32, count int32, value *int32) { gpUniform3iv(location, count, value) }
func Uniform3ui(location int32, v0 uint32, v1 uint32, v2 uint32) { gpUniform3ui(location, v0, v1, v2) }
func Uniform3uiv(location int32, count int32, value *uint32) { gpUniform3uiv(location, count, value) }
func Uniform4f(location int32, v0 float32, v1 float32, v2 float32, v3 float32) { gpUniform4f(location, v0, v1, v2, v3) }
func Uniform4fv(location int32, count int32, value *float32) { gpUniform4fv(location, count, value) }
func Uniform4i(location int32, v0 int32, v1 int32, v2 int32, v3 int32) { gpUniform4i(location, v0, v1, v2, v3) }
func Uniform4iv(location int32, count int32, value *int32) { gpUniform4iv(location, count, value) }
func Uniform4ui(location int32, v0 uint32, v1 uint32, v2 uint32, v3 uint32) { gpUniform4ui(location, v0, v1, v2, v3) }
func Uniform4uiv(location int32, count int32, value *uint32) { gpUniform4uiv(location, count, value) }
func UniformBlockBinding(program uint32, uniformBlockIndex uint32, uniformBlockBinding uint32) { gpUniformBlockBinding(program, uniformBlockIndex, uniformBlockBinding) }
func UniformMatrix2fv(location int32, count int32, transpose bool, value *float32) { gpUniformMatrix2fv(location, count, transpose, value) }
func UniformMatrix2x3fv(location int32, count int32, transpose bool, value *float32) { gpUniformMatrix2x3fv(location, count, transpose, value) }
func UniformMatrix2x4fv(location int32, count int32, transpose bool, value *float32) { gpUniformMatrix2x4fv(location, count, transpose, value) }
func UniformMatrix3fv(location int32, count int32, transpose bool, value *float32) { gpUniformMatrix3fv(location, count, transpose, value) }
func UniformMatrix3x2fv(location int32, count int32, transpose bool, value *float32) { gpUniformMatrix3x2fv(location, count, transpose, value) }
func UniformMatrix3x4fv(location int32, count int32, transpose bool, value *float32) { gpUniformMatrix3x4fv(location, count, transpose, value) }
func UniformMatrix4fv(location int32, count int32, transpose bool, value *float32) { gpUniformMatrix4fv(location, count, transpose, value) }
func UniformMatrix4x2fv(location int32, count int32, transpose bool, value *float32) { gpUniformMatrix4x2fv(location, count, transpose, value) }
func UniformMatrix4x3fv(location int32, count int32, transpose bool, value *float32) { gpUniformMatrix4x3fv(location, count, transpose, value) }
func UnmapBuffer(target uint32) bool { return gpUnmapBuffer(target) }
func UseProgram(program uint32) { gpUseProgram(program) }
func UseProgramStages(pipeline uint32, stages uint32, program uint32) { gpUseProgramStages(pipeline, stages, program) }
func ValidateProgram(program uint32) { gpValidateProgram(program) }
func ValidateProgramPipeline(pipeline uint32) { gpValidateProgramPipeline(pipeline) }
func VertexAttrib1f(index uint32, x float32) { gpVertexAttrib1f(index, x) }
func VertexAttrib1fv(index uint32, v *float32) { gpVertexAttrib1fv(index, v) }
func VertexAttrib2f(index uint32, x float32, y float32) { gpVertexAttrib2f(index, x, y) }
func VertexAttrib2fv(index uint32, v *float32) { gpVertexAttrib2fv(index, v) }
func VertexAttrib3f(index uint32, x float32, y float32, z float32) { gpVertexAttrib3f(index, x, y, z) }
func VertexAttrib3fv(index uint32, v *float32) { gpVertexAttrib3fv(index, v) }
func VertexAttrib4f(index uint32, x float32, y float32, z float32, w float32) { gpVertexAttrib4f(index, x, y, z, w) }
func VertexAttrib4fv(index uint32, v *float32) { gpVertexAttrib4fv(index, v) }
func VertexAttribBinding(attribindex uint32, bindingindex uint32) { gpVertexAttribBinding(attribindex, bindingindex) }
func VertexAttribDivisor(index uint32, divisor uint32) { gpVertexAttribDivisor(index, divisor) }
func VertexAttribFormat(attribindex uint32, size int32, xtype uint32, normalized bool, relativeoffset uint32) { gpVertexAttribFormat(attribindex, size, xtype, normalized, relativeoffset) }
func VertexAttribI4i(index uint32, x int32, y int32, z int32, w int32) { gpVertexAttribI4i(index, x, y, z, w) }
func VertexAttribI4iv(index uint32, v *int32) { gpVertexAttribI4iv(index, v) }
func VertexAttribI4ui(index uint32, x uint32, y uint32, z uint32, w uint32) { gpVertexAttribI4ui(index, x, y, z, w) }
func VertexAttribI4uiv(index uint32, v *uint32) { gpVertexAttribI4uiv(index, v) }
func VertexAttribIFormat(attribindex uint32, size int32, xtype uint32, relativeoffset uint32) { gpVertexAttribIFormat(attribindex, size, xtype, relativeoffset) }
func VertexAttribIPointer(index uint32, size int32, xtype uint32, stride int32, pointer unsafe.Pointer) { gpVertexAttribIPointer(index, size, xtype, stride, pointer) }
func VertexAttribPointer(index uint32, size int32, xtype uint32, normalized bool, stride int32, pointer unsafe.Pointer) { gpVertexAttribPointer(index, size, xtype, normalized, stride, pointer) }
func VertexBindingDivisor(bindingindex uint32, divisor uint32) { gpVertexBindingDivisor(bindingindex, divisor) }
func Viewport(x int32, y int32, width int32, height int32) { gpViewport(x, y, width, height) }
func WaitSync(sync uintptr, flags uint32, timeout uint64) { gpWaitSync(sync, flags, timeout) }
